### ISSUE TITLE
const awareness in API

### ISSUE THREAD

**Issue by n0la** [x86-64/mustache-c#7]
Some functions signatures would benefit from having some of their parameters declared `const`. These include:
- `buffer` in `mustache_api_write`
- `error` in `mustache_api_error`

It is especially important (imho) for `write`, as sometimes you have to explicitly cast the const away on static buffers when calling `write` as seen [here](https://github.com/x86-64/mustache-c/blob/master/examples/array.c#L90).

This breaks API, as existing code that already casts will break; but it would make code overall cleaner. ABI is not broken. 

I wanted to bring this up in an issue first before making a merge request for it. What do you think?

**Comment by x86-64** [comment]
Const sounds good, so if you have time to work on this that would be 
nice. Thanks for earlier patches too.

**Comment by n0la** [comment]
You are more than welcome. I like mustache-c for the sleek and clean C API and it works flawlessly in and for my project.
